services:
  app:
    image: backend:${TAG}
    restart: unless-stopped
    command:
      [
        "--bind",
        "0.0.0.0:8000",
        "--workers",
        "${WORKERS:-1}",
        "--worker-class",
        "uvicorn.workers.UvicornWorker",
        "--max-requests",
        "1000",
        "--max-requests-jitter",
        "100",
        "--graceful-timeout",
        "5",
        "--keep-alive",
        "300",
        "--forwarded-allow-ips",
        "*",
      ]

    shm_size: '2gb'

    ports:
      - ${LISTEN:-80}:8000

    volumes:
      - ./data/postgres:/app/data/postgres16
      - ./data/postgres17:/app/data/postgres
      - /mnt/data/${TAG}/photos:/app/data/photos
