version: '3'
services:
    db:
        restart: always
        image: "postgis/postgis:14-3.2"
        shm_size: "512mb"
        env_file:
            - .env
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
        command: -p ${POSTGRES_PORT}
        networks:
            - prod-net
    backend:
        restart: always
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: ./docker-entrypoint.sh
        networks:
            - prod-net
        environment:
            DEV: 0

    nginx:
        restart: always
        image: nginx:1.23.1-alpine
        ports:
            - ${PORT:-80}:80
        volumes:
            - ./nginx/nginx-proxy-prod.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
          - backend
        networks:
            - prod-net

networks:
    prod-net: