version: "3"

services:
  app:
    image: backend:${TAG}
    restart: unless-stopped
    command:
      [
        "--workers",
        "${WORKERS:-1}",
        "--timeout-keep-alive",
        "300",
        "--timeout-graceful-shutdown",
        "5",
        "--proxy-headers",
        "--forwarded-allow-ips",
        "*",
      ]

    ports:
      - ${LISTEN:-80}:8000

    volumes:
      - ./data/postgres:/app/data/postgres
      - /mnt/data/${TAG}/photos:/app/data/photos
