version: '3'
services:
    db:
        restart: always
        image: "postgis/postgis:14-3.2"
        shm_size: "512mb"
        env_file:
            - .env
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
        command: -p ${POSTGRES_PORT}
        networks:
            - dev-net
    backend:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        env_file:
            - .env
        volumes:
            - ./backend:/app/backend
            - ./migrations:/app/migrations
            - ./alembic.ini:/app/alembic.ini
        command: ./docker-entrypoint.sh
        networks:
            - dev-net
        environment:
            DEV: 1

    nginx:
        restart: always
        image: nginx:1.23.1-alpine
        ports:
            - 8080:80
        volumes:
            - ./nginx/nginx-proxy-dev.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
          - backend
        networks:
            - dev-net

networks:
    dev-net: