version: "3.9"

services:
  db:
    image: mongo
    restart: unless-stopped
    command:
      [
        "mongod",
        "--bind_ip_all",
        "--setParameter",
        "transactionLifetimeLimitSeconds=90",
        "--replSet",
        "rs0",
      ]

    volumes:
      - ./data/db:/data/db

  db-setup:
    image: mongo
    entrypoint: ["/bin/sh", "/mongo-init-replica.sh"]
    command: ["db:27017"]

    depends_on:
      - db

    volumes:
      - ./scripts/mongo-init-replica.sh:/mongo-init-replica.sh:ro

  app:
    build: .
    restart: unless-stopped
    command:
      [
        "pipenv run uvicorn main:app --host 0.0.0.0 --workers 24 --timeout-keep-alive 300 --timeout-graceful-shutdown 5 --no-server-header",
      ]

    depends_on:
      - db

    environment:
      MONGO_HOST: db

    ports:
      - ${LISTEN:-80}:8000
