"""added tiles expired queue table

Revision ID: 656be64c79a3
Revises: 6869b62d529b
Create Date: 2022-12-14 21:10:09.732006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "656be64c79a3"
down_revision = "6869b62d529b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tiles_queue",
        sa.Column("z", sa.SMALLINT(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("inserted_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("z", "x", "y"),
        prefixes=["UNLOGGED"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tiles_queue")
    # ### end Alembic commands ###
