"""added more fields to osm_nodes

Revision ID: 9e2034191715
Revises: 1383818297e9
Create Date: 2022-12-24 00:35:40.668399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2034191715'
down_revision = '1383818297e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('osm_nodes', sa.Column('version_1_ts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('osm_nodes', sa.Column('version_last_ts', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('osm_nodes', 'version_last_ts')
    op.drop_column('osm_nodes', 'version_1_ts')
    # ### end Alembic commands ###
