name: Test in CI

on:
  push:
    # branches-ignore:
    # - main
    # - dev
    paths:
    - backend/**
    - requirements.txt
    - .github/workflows/ci_test.yml
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
      python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: python -m unittest
    - name: Run linter
      run: black --check .
