name: deploy-main

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  deploy:
    name: Deploy main
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.SSH_HOST_NEW_IP }}
          ssh-port: ${{ secrets.SSH_HOST_NEW_PORT }}
      - name: Run deploy script on host
        run: |
          ssh -p ${{ secrets.SSH_HOST_NEW_PORT }} -l ${{ secrets.SSH_USER_NEW }} ${{ secrets.SSH_HOST_NEW_IP }} << EOF
            set -e
            cd /home/${{ secrets.SSH_USER_NEW }}/main/
            git fetch
            git checkout origin/main
            PORT=49222 docker-compose -f docker-compose-prod.yml -p prod up -d --build
          EOF